name: scienceapp
description: A new Flutter project.
version: 1.0.0+1
license: MIT

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  clipboard_manager: ^0.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Spectral
      fonts:
      - asset: fonts/Spectral-Regular.ttf